package excecao;

public class Causa {

	public static void main(String[] args) {
		try {
			metodoA(null);
		} catch (Exception e) {
			if(e.getCause() != null) {
				System.out.println(e.getCause().getMessage());
			}
		}
	}
	
	public static void metodoA(Aluno aluno) {
		try {
			metodoB(aluno);
		} catch (Exception e) {
			throw new IllegalArgumentException(e);
		}
	}
	
	public static void metodoB(Aluno aluno) {
		if(aluno == null) {
			throw new NullPointerException("Aluno est√° nulo");
		}
	}
}
